version: '3'

x-default-options: &default-options
    networks:
        - dcm
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - type: bind
          source: .
          target: /app
        - ./static:/static:delegated
        - node-modules-data:/app/node_modules

name: dcm
services:
#    client:
#        container_name: dcm-client
#        command: npm run nx run client:serve -- --verbose
#        ports:
#            - 3000:3000
#        <<: *default-options

    # api:
    #     build:
    #         context: api
    #         dockerfile: Dockerfile.dev
    #     command: sh -c "cargo watch -x run"
    #     env_file:
    #         - ./api/.env
    #     networks:
    #         - chat-wall
    #     volumes:
    #         - ./api:/app
    #         - api-cache:/app/target
    #     ports:
    #         - 8000:8000
    #     depends_on:
    #         - postgres

    postgres:
        image: postgres:15-alpine
        container_name: dcm-postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: dcm
            POSTGRES_USER: dcm
            POSTGRES_DB: dcm
        networks:
            - dcm
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data

    minio:
        image: quay.io/minio/minio
        container_name: dcm-minio
        command: server /data --console-address ":9001"
        restart: always
        environment:
            MINIO_ROOT_USER: dcm
            MINIO_ROOT_PASSWORD: dcm-password
        networks:
            - dcm
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./minio:/data

    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: dcm-jaeger
        ports:
          - 16686:16686
          - 4317:4317
          - 4318:4318
        environment:
          - COLLECTOR_OTLP_ENABLED=true
        networks:
          - dcm

networks:
    dcm: {}

volumes:
    node-modules-data:

