version: '3'

x-default-options: &default-options
    networks:
        - ibs
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - ./:/app
        - ./static:/static:delegated
        - node-modules-data:/app/node_modules

name: ibs
services:
    client:
        container_name: ibs-client
        command: npm run nx run client:serve -- --verbose
        ports:
            - 3000:3000
        <<: *default-options

    # api:
    #     build:
    #         context: api
    #         dockerfile: Dockerfile.dev
    #     command: sh -c "cargo watch -x run"
    #     env_file:
    #         - ./api/.env
    #     networks:
    #         - chat-wall
    #     volumes:
    #         - ./api:/app
    #         - api-cache:/app/target
    #     ports:
    #         - 8000:8000
    #     depends_on:
    #         - postgres

    postgres:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ibs
            POSTGRES_USER: ibs
            POSTGRES_DB: ibs
        networks:
            - ibs
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
          - 16686:16686
          - 4317:4317
          - 4318:4318
        environment:
          - COLLECTOR_OTLP_ENABLED=true
        networks:
          - ibs

networks:
    ibs: {}

volumes:
    node-modules-data:

