name: deploy
on:
    push:
        tags:
            - v*

jobs:
    push_api_to_registry:
        name: build api
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Deploy
              uses: "./.github/templates/deploy"
              with:
                  dockerUsername: ${{ secrets.DOCKER_USERNAME }}
                  dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
                  imageName: hybridfox/ibs-api
                  context: ./apps/api/.
                  file: ./Dockerfile

    push_client_to_registry:
        name: build client
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Deploy
              uses: "./.github/templates/deploy"
              with:
                  dockerUsername: ${{ secrets.DOCKER_USERNAME }}
                  dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
                  imageName: hybridfox/ibs-client
                  context: .
                  file: ./apps/client/Dockerfile
    # deploy:
    #     needs: [push_api_to_registry, push_client_to_registry]
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: curl
    #           uses: wei/curl@v1
    #           with:
    #               args: -X POST ${{ secrets.RANCHER_DEPLOY_URL }}
